name: Build, test and deliver container

on: push
#on: push: branches: -main

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Java 11 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11 #pipeline moet op java11 runnen, anders werkt SonarCloud niet
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start PostgreSQL for integration test
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql user: 'postgres' #${{ secrets.POSTGRESQL_ROOT_USER }}
          postgresql password: 'abc123' #${{ secrets.POSTGRESQL_ROOT_PASSWORD }}
          postgresql db: 'albums'
          #mysql root password: #${{ secrets.POSTGRESQL_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Cache SonarCloud packages #cashing -> 2e keer builden gaat sneller
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: Build, test, analyse and package project
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Britt93_APT-Album-Service

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/APT-Album-Service:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/APT-Album-Service:latest